### ISSUE TITLE
dependencies: gulp-minify-css deprecation

### ISSUE THREAD

**Issue by scniro** [mtfranchetto/smild#1]
[gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css) has been in deprecated in favor of [gulp-clean-css](https://github.com/scniro/gulp-clean-css). Please open an [issue](https://github.com/scniro/gulp-clean-css/issues) with the new repository if you do upgrade and experience any unexpected behavior. I look forward to maintaining this package moving forward.

**Comment by mtfranchetto** [comment]
Thanks, replaced in 1f7889680ebaf0d7cd03dbf3672139962d614d96.
