### ISSUE TITLE
How to exclude a file from minification

### ISSUE THREAD

**Issue by Naikno** [mtfranchetto/smild#10]
Hi! ,
there is a way to ignore some js file from minification by smildfile.js?
something like "!" notation in gulp : gulp.src(['js/**/*.js', '!js/**/fileToIgnore.js']).
Thanks in advance

**Comment by mtfranchetto** [comment]
Currently is not possibile because the pipeline creates the entire bundle,
then minifies it. What you want to achieve is quite impossible.

-- 
Mattia

**Comment by Naikno** [comment]
Ok thanks !, and there is a possibility to ignore a file from the bundle?

**Comment by mtfranchetto** [comment]
In browserify yes, but in smild currently is not possibile. Feel free to
open a PR, it should be relatively simple.

-- 
Mattia
